### ISSUE TITLE
Not in list of proposals?

### ISSUE THREAD

**Issue by stevenvachon** [mmkal/proposal-multi-backtick-templates#7]
Why is this not in https://github.com/tc39/proposals?

**Comment by ljharb** [comment]
I assume because it has never had a TC39 champion nor been added to an agenda.

**Comment by jridgewell** [comment]
👋 I am the TC39 champion. Usually items are added to the proposals list after the first time they're presented to committee. Unfortunately, I've been busy with personal matters, so I haven't put this on the agenda yet.

At the last meeting, @hemanth mentioned he was interested in the proposal. Maybe he could put it on the agenda for next time?

**Comment by hemanth** [comment]
Sure @jridgewell I can present it in the next meeting.

**Comment by ljharb** [comment]
Thanks, TIL :-) once it's on an agenda, feel free to PR it into the stage 0 proposals list.

**Comment by hemanth** [comment]
We can close this now and then #14 as it has been approved to stage-1 now.

**Comment by ljharb** [comment]
Added to the list in https://github.com/tc39/proposals/commit/82910de8084607be3a2a9e411418ad5f336ca910.
